controllers:
    resource: ../src/Controller/
    type: annotation

admin:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /admin

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: "posts"
        permanent: true